Drop Elixir 1.11 support
The `erlef/setup-beam@v1` action fails with the following error:
> Error: Requested loose Erlang/OTP version (23.0) not found in version list

Based on [their readme][1], the earliest supported OTP version for the
latest Ubuntu is 24.3. And OTP 24 support was added in Elixir 1.12. So
we need to bump the oldest supported version to run these tests.

[1]: https://github.com/erlef/setup-beam?tab=readme-ov-file#compatibility-between-operating-system-and-erlangotp